---
abstract: 'Seamlessly Run LibZMQ Progs against LibZMQ3'
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZMQ-LibZMQ3-LibZMQ2
no_index:
  directory:
    - t
    - inc
requires:
  ZMQ::LibZMQ3: 0
  perl: 5.006
version: 0.01
